# Generated by Django 6.0.4 on 2026-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gopher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Hive username to hide (without @)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
